<a href="https://colab.research.google.com/github/dac0d3/490-Group2/blob/main/IntroToColab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:

import torch
import numpy as np


In [6]:
#List

my_list = [[1,2,3,4,5], [6,7,8,9,10]]
my_list


[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

In [14]:
# Numpy Array

np1 = np.random.rand(3,4)
np1
#np1.dtype

array([[0.16640162, 0.87030095, 0.40615333, 0.6695151 ],
       [0.23010689, 0.16836916, 0.03629927, 0.39100459],
       [0.22327975, 0.88276983, 0.06293947, 0.55645262]])

In [11]:
# Tensor

tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[ 0.0694, -0.7411,  0.5902,  0.2331],
        [ 0.9851, -1.2585, -0.2685, -0.4664],
        [-0.0513,  0.9928, -0.6785,  1.2897]])

In [15]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [16]:
## Create Tensor out of numpy array

my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.1664, 0.8703, 0.4062, 0.6695],
        [0.2301, 0.1684, 0.0363, 0.3910],
        [0.2233, 0.8828, 0.0629, 0.5565]], dtype=torch.float64)